// PLAYER
export const ADD_GOLD = 'ADD_GOLD';
export const REMOVE_GOLD = 'REMOVE_GOLD';
export const ADD_SILVER = 'ADD_SILVER';
export const REMOVE_SILVER = 'REMOVE_SILVER';
export const ADD_COPPER = 'ADD_COPPER';
export const REMOVE_COPPER = 'REMOVE_COPPER';
export const ADD_WEAPON = 'ADD_WEAPON';
export const REMOVE_WEAPON = 'REMOVE_WEAPON';
export const ADD_SHIELD = 'ADD_SHIELD';
export const REMOVE_SHIELD = 'REMOVE_SHIELD';
export const ADD_XP = 'ADD_XP';
export const CHANGE_ENTITY = 'CHANGE_ENTITY';
export const CHANGE_PLAYER_POSITION = 'CHANGE_PLAYER_POSITION';
export const CREATE_LEVEL = 'CREATE_LEVEL';
export const MODIFY_HEALTH = 'MODIFY_HEALTH';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const PLAYER_BOUGHT_ITEM = 'PLAYER_BOUGHT_ITEM';
export const PLAYER_SOLD_ITEM = 'PLAYER_SOLD_ITEM';
export const PLAYER_TRADE_SUCCESS = 'PLAYER_TRADE_SUCCESS';
export const PLAYER_TRADE_FAIL = 'PLAYER_TRADE_FAIL';
export const INTERACT_WITH_NEUTRAL = 'INTERACT_WITH_NEUTRAL';
export const TALK_TO_NPC = 'TALK_TO_NPC';
export const LOOK_AROUND = 'LOOK_AROUND';
export const LEVEL_EXIT = 'LEVEL_EXIT';
export const LEVEL_ENTER = 'LEVEL_ENTER';
export const PLAYER_SET_USERNAME = 'PLAYER_SET_USERNAME';

// USER
export const USER_TWITER_AUTH_REQUEST = 'USER_TWITER_AUTH_REQUEST';
export const USER_TWITER_AUTH_SUCCESS = 'USER_TWITER_AUTH_SUCCESS';
export const USER_TWITER_AUTH_FAIL = 'USER_TWITER_AUTH_FAIL';

// GAME
export const RESTART = 'RESTART';
export const TOGGLE_FOG_MODE = 'TOGGLE_FOG_MODE';
export const GAME_LOAD_REQUEST = 'GAME_LOAD_REQUEST';
export const GAME_LOAD_SUCCESS = 'GAME_LOAD_SUCCESS';
export const GAME_LOAD_FAIL = 'GAME_LOAD_FAIL';
export const GAME_SAVE_REQUEST = 'GAME_SAVE_REQUEST';
export const GAME_SAVE_SUCCESS = 'GAME_SAVE_SUCCESS';
export const GAME_SAVE_FAIL = 'GAME_SAVE_FAIL';


// DUNGEON
export const RESET_DUNGEON = 'RESET_DUNGEON';
export const SET_END_GAME = 'SET_END_GAME';
export const UPDATE_DUNGEON = 'UPDATE_DUNGEON';
export const SET_DUNGEON_LEVEL = 'SET_DUNGEON_LEVEL';

// NPC
export const TOGGLE_NPC_STORE = 'TOGGLE_NPC_STORE';
export const SELECT_NPC = 'SELECT_NPC';
export const NPC_BOUGHT_ITEM = 'NPC_BOUGHT_ITEM';
export const NPC_SOLD_ITEM = 'NPC_SOLD_ITEM';
export const NPC_TRADED_ITEM = 'NPC_TRADED_ITEM';

